module Tables exposing (tables)

import Array
import Dict exposing (..)
import Random


tables =
    Dict.fromList
        [ ( "CitR: Actions", askCitrActions )
        , ( "CitR: Focus", askCitrFocus )
        , ( "Mythic 2e: Actions", askMythicActions )
        , ( "Mythic 2e: Descritions", askMythicDescriptions )
        ]


askCitrActions =
    Random.int 0 (Array.length citrActions - 1) |> Random.map (\i -> Array.get i citrActions |> Maybe.withDefault "")


askCitrFocus =
    Random.int 0 (Array.length citrFocus - 1) |> Random.map (\i -> Array.get i citrFocus |> Maybe.withDefault "")


askMythicActions =
    let
        action1 =
            Random.int 0 (Array.length mythicAction1 - 1) |> Random.map (\i -> Array.get i mythicAction1 |> Maybe.withDefault "")

        action2 =
            Random.int 0 (Array.length mythicAction2 - 1) |> Random.map (\i -> Array.get i mythicAction2 |> Maybe.withDefault "")
    in
    Random.map2 (\a1 a2 -> a1 ++ " " ++ a2) action1 action2


askMythicDescriptions =
    let
        desc1 =
            Random.int 0 (Array.length mythicDescriptor1 - 1) |> Random.map (\i -> Array.get i mythicDescriptor1 |> Maybe.withDefault "")

        desc2 =
            Random.int 0 (Array.length mythicDescriptor2 - 1) |> Random.map (\i -> Array.get i mythicDescriptor2 |> Maybe.withDefault "")
    in
    Random.map2 (\d1 d2 -> d1 ++ " " ++ d2) desc1 desc2


citrActions =
    Array.fromList
        [ "Abandon"
        , "Acquire"
        , "Arrive"
        , "Attack"
        , "Capture"
        , "Chase"
        , "Confront"
        , "Control"
        , "Create"
        , "Deliver"
        , "Demand"
        , "Disguise"
        , "Eliminate"
        , "Escort"
        , "Evade"
        , "Explore"
        , "Focus"
        , "Guard"
        , "Hide"
        , "Impress"
        , "Improve"
        , "Investigate"
        , "Leave"
        , "Locate"
        , "Manipulate"
        , "Prevent"
        , "Protect"
        , "Restore"
        , "Reveal"
        , "Search"
        , "Share"
        , "Steal"
        , "Support"
        , "Trap"
        , "Trick"
        , "Uncover"
        ]


citrFocus =
    Array.fromList
        [ "Bravery"
        , "Burden"
        , "Clue"
        , "Court"
        , "Death"
        , "Deception"
        , "Doubt"
        , "Fear"
        , "Fight"
        , "Followers"
        , "Gadget"
        , "Hate"
        , "History"
        , "Insight"
        , "Knowledge"
        , "Life"
        , "Love"
        , "Message"
        , "Mystery"
        , "Obligation"
        , "Opportunity"
        , "Patron"
        , "Plan"
        , "Power"
        , "Refuge"
        , "Relationship"
        , "Reputation"
        , "Risk"
        , "Route"
        , "Secret"
        , "Skill"
        , "Treasure"
        , "Trust"
        , "Truth"
        , "Wealth"
        , "Weapon"
        ]


mythicAction1 =
    Array.fromList
        [ "Abandon"
        , "Accompany"
        , "Activate"
        , "Agree"
        , "Ambush"
        , "Arrive"
        , "Assist"
        , "Attack"
        , "Attain"
        , "Bargain"
        , "Befriend"
        , "Bestow"
        , "Betray"
        , "Block"
        , "Break"
        , "Carry"
        , "Celebrate"
        , "Change"
        , "Close"
        , "Combine"
        , "Communicate"
        , "Conceal"
        , "Continue"
        , "Control"
        , "Create"
        , "Deceive"
        , "Decrease"
        , "Defend"
        , "Delay"
        , "Deny"
        , "Depart"
        , "Deposit"
        , "Destroy"
        , "Dispute"
        , "Disrupt"
        , "Distrust"
        , "Divide"
        , "Drop"
        , "Easy"
        , "Energize"
        , "Escape"
        , "Expose"
        , "Fail"
        , "Fight"
        , "Flee"
        , "Free"
        , "Guide"
        , "Harm"
        , "Heal"
        , "Hinder"
        , "Imitate"
        , "Imprison"
        , "Increase"
        , "Indulge"
        , "Inform"
        , "Inquire"
        , "Inspect"
        , "Invade"
        , "Leave"
        , "Lure"
        , "Misuse"
        , "Move"
        , "Neglect"
        , "Observe"
        , "Open"
        , "Oppose"
        , "Overthrow"
        , "Praise"
        , "Proceed"
        , "Protect"
        , "Punish"
        , "Pursue"
        , "Recruit"
        , "Refuse"
        , "Release"
        , "Relinquish"
        , "Repair"
        , "Repulse"
        , "Return"
        , "Reward"
        , "Ruin"
        , "Separate"
        , "Start"
        , "Stop"
        , "Strange"
        , "Struggle"
        , "Succeed"
        , "Support"
        , "Suppress"
        , "Take"
        , "Threaten"
        , "Transform"
        , "Trap"
        , "Travel"
        , "Triumph"
        , "Truce"
        , "Trust"
        , "Use"
        , "Usurp"
        , "Waste"
        ]


mythicAction2 =
    Array.fromList
        [ "Advantage"
        , "Adversity"
        , "Agreement"
        , "Animal"
        , "Attention"
        , "Balance"
        , "Battle"
        , "Benefits"
        , "Building"
        , "Burden"
        , "Bureaucracy"
        , "Business"
        , "Chaos"
        , "Comfort"
        , "Completion"
        , "Conflict"
        , "Cooperation"
        , "Danger"
        , "Defense"
        , "Depletion"
        , "Disadvantage"
        , "Distraction"
        , "Elements"
        , "Emotion"
        , "Enemy"
        , "Energy"
        , "Environment"
        , "Expectation"
        , "Exterior"
        , "Extravagance"
        , "Failure"
        , "Fame"
        , "Fear"
        , "Freedom"
        , "Friend"
        , "Goal"
        , "Group"
        , "Health"
        , "Hindrance"
        , "Home"
        , "Hope"
        , "Idea"
        , "Illness"
        , "Illusion"
        , "Individual"
        , "Information"
        , "Innocent"
        , "Intellect"
        , "Interior"
        , "Investment"
        , "Leadership"
        , "Legal"
        , "Location"
        , "Military"
        , "Misfortune"
        , "Mundane"
        , "Nature"
        , "Needs"
        , "News"
        , "Normal"
        , "Object"
        , "Obscurity"
        , "Official"
        , "Opposition"
        , "Outside"
        , "Pain"
        , "Path"
        , "Peace"
        , "People"
        , "Personal"
        , "Physical"
        , "Plot"
        , "Portal"
        , "Possessions"
        , "Poverty"
        , "Power"
        , "Prison"
        , "Project"
        , "Protection"
        , "Reassurance"
        , "Representative"
        , "Riches"
        , "Safety"
        , "Strength"
        , "Success"
        , "Suffering"
        , "Surprise"
        , "Tactic"
        , "Technology"
        , "Tension"
        , "Time"
        , "Trial"
        , "Value"
        , "Vehicle"
        , "Victory"
        , "Vulnerability"
        , "Weapon"
        , "Weather"
        , "Work"
        , "Wound"
        ]


mythicDescriptor1 =
    Array.fromList
        [ "Adventurously"
        , "Aggressively"
        , "Anxiously"
        , "Awkwardly"
        , "Beautifully"
        , "Bleakly"
        , "Boldly"
        , "Bravely"
        , "Busily"
        , "Calmly"
        , "Carefully"
        , "Carelessly"
        , "Cautiously"
        , "Ceaselessly"
        , "Cheerfully"
        , "Combatively"
        , "Coolly"
        , "Crazily"
        , "Curiously"
        , "Dangerously"
        , "Defiantly"
        , "Deliberately"
        , "Delicately"
        , "Delightfully"
        , "Dimly"
        , "Efficiently"
        , "Emotionally"
        , "Energetically"
        , "Enormously"
        , "Enthusiastically"
        , "Excitedly"
        , "Fearfully"
        , "Ferociously"
        , "Fiercely"
        , "Foolishly"
        , "Fortunately"
        , "Frantically"
        , "Freely"
        , "Frighteningly"
        , "Fully"
        , "Generously"
        , "Gently"
        , "Gladly"
        , "Gracefully"
        , "Gratefully"
        , "Happily"
        , "Hastily"
        , "Healthily"
        , "Helpfully"
        , "Helplessly"
        , "Hopelessly"
        , "Innocently"
        , "Intensely"
        , "Interestingly"
        , "Irritatingly"
        , "Joyfully"
        , "Kindly"
        , "Lazily"
        , "Lightly"
        , "Loosely"
        , "Loudly"
        , "Lovingly"
        , "Loyally"
        , "Majestically"
        , "Meaningfully"
        , "Mechanically"
        , "Mildly"
        , "Miserably"
        , "Mockingly"
        , "Mysteriously"
        , "Naturally"
        , "Neatly"
        , "Nicely"
        , "Oddly"
        , "Offensively"
        , "Officially"
        , "Partially"
        , "Passively"
        , "Peacefully"
        , "Perfectly"
        , "Playfully"
        , "Politely"
        , "Positively"
        , "Powerfully"
        , "Quaintly"
        , "Quarrelsomely"
        , "Quietly"
        , "Roughly"
        , "Rudely"
        , "Ruthlessly"
        , "Slowly"
        , "Softly"
        , "Strangely"
        , "Swiftly"
        , "Threateningly"
        , "Timidly"
        , "Very"
        , "Violently"
        , "Wildly"
        , "Yieldingly"
        ]


mythicDescriptor2 =
    Array.fromList
        [ "Abnormal"
        , "Amusing"
        , "Artificial"
        , "Average"
        , "Beautiful"
        , "Bizarre"
        , "Boring"
        , "Bright"
        , "Broken"
        , "Clean"
        , "Cold"
        , "Colorful"
        , "Colorless"
        , "Comforting"
        , "Creepy"
        , "Cute"
        , "Damaged"
        , "Dark"
        , "Defeated"
        , "Dirty"
        , "Disagreeable"
        , "Dry"
        , "Dull"
        , "Empty"
        , "Enormous"
        , "Extraordinary"
        , "Extravagant"
        , "Faded"
        , "Familiar"
        , "Fancy"
        , "Feeble"
        , "Festive"
        , "Flawless"
        , "Forlorn"
        , "Fragile"
        , "Fragrant"
        , "Fresh"
        , "Full"
        , "Glorious"
        , "Graceful"
        , "Hard"
        , "Harsh"
        , "Healthy"
        , "Heavy"
        , "Historical"
        , "Horrible"
        , "Important"
        , "Interesting"
        , "Juvenile"
        , "Lacking"
        , "Large"
        , "Lavish"
        , "Lean"
        , "Less"
        , "Lethal"
        , "Lively"
        , "Lonely"
        , "Lovely"
        , "Magnificent"
        , "Mature"
        , "Messy"
        , "Mighty"
        , "Military"
        , "Modern"
        , "Mundane"
        , "Mysterious"
        , "Natural"
        , "Normal"
        , "Odd"
        , "Old"
        , "Pale"
        , "Peaceful"
        , "Petite"
        , "Plain"
        , "Poor"
        , "Powerful"
        , "Protective"
        , "Quaint"
        , "Rare"
        , "Reassuring"
        , "Remarkable"
        , "Rotten"
        , "Rough"
        , "Ruined"
        , "Rustic"
        , "Scary"
        , "Shocking"
        , "Simple"
        , "Small"
        , "Smooth"
        , "Soft"
        , "Strong"
        , "Stylish"
        , "Unpleasant"
        , "Valuable"
        , "Vibrant"
        , "Warm"
        , "Watery"
        , "Weak"
        , "Young"
        ]
