module Tables exposing (tables)

import Array
import Dict exposing (..)


tables = Dict.fromList
    [ ( "CitR: Actions", citr_actions )
    , ( "CitR: Focus", citr_focus )
    ]

citr_actions = Array.fromList
    [ "Abandon"
    , "Acquire"
    , "Arrive"
    , "Attack"
    , "Capture"
    , "Chase"
    , "Confront"
    , "Control"
    , "Create"
    , "Deliver"
    , "Demand"
    , "Disguise"
    , "Eliminate"
    , "Escort"
    , "Evade"
    , "Explore"
    , "Focus"
    , "Guard"
    , "Hide"
    , "Impress"
    , "Improve"
    , "Investigate"
    , "Leave"
    , "Locate"
    , "Manipulate"
    , "Prevent"
    , "Protect"
    , "Restore"
    , "Reveal"
    , "Search"
    , "Share"
    , "Steal"
    , "Support"
    , "Trap"
    , "Trick"
    , "Uncover"
    ]

citr_focus = Array.fromList
    [ "Bravery"
    , "Burden"
    , "Clue"
    , "Court"
    , "Death"
    , "Deception"
    , "Doubt"
    , "Fear"
    , "Fight"
    , "Followers"
    , "Gadget"
    , "Hate"
    , "History"
    , "Insight"
    , "Knowledge"
    , "Life"
    , "Love"
    , "Message"
    , "Mystery"
    , "Obligation"
    , "Opportunity"
    , "Patron"
    , "Plan"
    , "Power"
    , "Refuge"
    , "Relationship"
    , "Reputation"
    , "Risk"
    , "Route"
    , "Secret"
    , "Skill"
    , "Treasure"
    , "Trust"
    , "Truth"
    , "Wealth"
    , "Weapon"
    ]
